/* Generated By:JavaCC: Do not edit this line. CompiladorTreeConstants.java Version 5.0 */
package javacc;

public interface CompiladorTreeConstants
{
  public int JJTCOMPILAR = 0;
  public int JJTIDENTIFICADOR = 1;
  public int JJTVOID = 2;
  public int JJTLITERALINTEGER = 3;
  public int JJTLITERALFLOAT = 4;
  public int JJTLITERALCARACTER = 5;
  public int JJTLITERALSTRING = 6;
  public int JJTLITERALBOOLEAN = 7;
  public int JJTLITERALNULL = 8;
  public int JJTTIPO = 9;
  public int JJTTIPO_PRIMITIVO = 10;
  public int JJTCAMPO_DECLARACION = 11;
  public int JJTDECLARADOR_VARIABLE_ID = 12;
  public int JJTINICIAR_VARIABLE = 13;
  public int JJTASIGNACION = 14;
  public int JJTOR = 15;
  public int JJTAND = 16;
  public int JJTBOR = 17;
  public int JJTXOR = 18;
  public int JJTBAND = 19;
  public int JJTIGUALIGUAL = 20;
  public int JJTNIGUAL = 21;
  public int JJTEXPRESION_INSTANCEOF = 22;
  public int JJTMENOR = 23;
  public int JJTMAYOR = 24;
  public int JJTMENOREQ = 25;
  public int JJTMAYOREQ = 26;
  public int JJTDESPI = 27;
  public int JJTDESPD = 28;
  public int JJTDESPDNS = 29;
  public int JJTADD = 30;
  public int JJTSUB = 31;
  public int JJTMULT = 32;
  public int JJTDIV = 33;
  public int JJTMOD = 34;
  public int JJTUNARYADD = 35;
  public int JJTUNARYSUB = 36;
  public int JJTPLUSPLUS = 37;
  public int JJTSUBSUB = 38;
  public int JJTCOMP = 39;
  public int JJTNOT = 40;
  public int JJTEXPRESION_ASIGNACION_ARRAY = 41;
  public int JJTDECLARACION_VARIABLE_LOCAL = 42;
  public int JJTEXPRESION_SENTENCIA = 43;
  public int JJTSENTENCIA_SWITCH = 44;
  public int JJTETIQUETA_SWITCH = 45;
  public int JJTSENTENCIA_IF = 46;
  public int JJTSENTENCIA_WHILE = 47;
  public int JJTSENTENCIA_DO = 48;
  public int JJTSENTENCIA_FOR = 49;
  public int JJTSENTENCIA_BREAK = 50;
  public int JJTSENTENCIA_CONTINUE = 51;
  public int JJTSENTENCIA_RETURN = 52;
  public int JJTSENTENCIA_THROW = 53;
  public int JJTSENTENCIA_SYNCHRONIZED = 54;
  public int JJTSENTENCIA_TRY = 55;


  public String[] jjtNodeName = {
    "compilar",
    "identificador",
    "void",
    "LiteralInteger",
    "LiteralFloat",
    "LiteralCaracter",
    "LiteralString",
    "LiteralBoolean",
    "LiteralNull",
    "tipo",
    "tipo_primitivo",
    "campo_declaracion",
    "declarador_variable_id",
    "iniciar_variable",
    "asignacion",
    "Or",
    "And",
    "BOr",
    "XOr",
    "BAnd",
    "IgualIgual",
    "NIgual",
    "expresion_instanceof",
    "Menor",
    "Mayor",
    "MenorEq",
    "MayorEq",
    "DespI",
    "DespD",
    "DespDNS",
    "Add",
    "Sub",
    "Mult",
    "Div",
    "Mod",
    "UnaryAdd",
    "UnarySub",
    "PlusPlus",
    "SubSub",
    "Comp",
    "Not",
    "expresion_asignacion_array",
    "declaracion_variable_local",
    "expresion_sentencia",
    "sentencia_switch",
    "etiqueta_switch",
    "sentencia_if",
    "sentencia_while",
    "sentencia_do",
    "sentencia_for",
    "sentencia_break",
    "sentencia_continue",
    "sentencia_return",
    "sentencia_throw",
    "sentencia_synchronized",
    "sentencia_try",
  };
}
/* JavaCC - OriginalChecksum=ed2983b5ac576f80b376ffc8cf419b58 (do not edit this line) */
