/* Generated By:JavaCC: Do not edit this line. CompiladorTreeConstants.java Version 5.0 */
package javacc;

public interface CompiladorTreeConstants
{
  public int JJTCOMPILAR = 0;
  public int JJTIDENTIFICADOR = 1;
  public int JJTVOID = 2;
  public int JJTLITERALINTEGER = 3;
  public int JJTLITERALFLOAT = 4;
  public int JJTLITERALCARACTER = 5;
  public int JJTLITERALSTRING = 6;
  public int JJTLITERALBOOLEAN = 7;
  public int JJTLITERALNULL = 8;
  public int JJTTIPO = 9;
  public int JJTTIPO_PRIMITIVO = 10;
  public int JJTCAMPO_DECLARACION = 11;
  public int JJTDECLARADOR_VARIABLE = 12;
  public int JJTDECLARADOR_VARIABLE_ID = 13;
  public int JJTINICIAR_VARIABLE = 14;
  public int JJTASIGNACION = 15;
  public int JJTOP_MULT_E = 16;
  public int JJTOP_ADD_E = 17;
  public int JJTOR = 18;
  public int JJTAND = 19;
  public int JJTBOR = 20;
  public int JJTXOR = 21;
  public int JJTBAND = 22;
  public int JJTIGUALIGUAL = 23;
  public int JJTNIGUAL = 24;
  public int JJTMENOR = 25;
  public int JJTMAYOR = 26;
  public int JJTMENOREQ = 27;
  public int JJTMAYOREQ = 28;
  public int JJTDESPI = 29;
  public int JJTDESPD = 30;
  public int JJTDESPDNS = 31;
  public int JJTADD = 32;
  public int JJTSUB = 33;
  public int JJTMULT = 34;
  public int JJTDIV = 35;
  public int JJTMOD = 36;
  public int JJTUNARYADD = 37;
  public int JJTUNARYSUB = 38;
  public int JJTPLUSPLUS = 39;
  public int JJTSUBSUB = 40;
  public int JJTCOMP = 41;
  public int JJTNOT = 42;
  public int JJTEXPRESION_ASIGNACION = 43;
  public int JJTSENTENCIA_VACIA = 44;
  public int JJTEXPRESION_SENTENCIA = 45;
  public int JJTSENTENCIA_SWITCH = 46;
  public int JJTETIQUETA_SWITCH = 47;
  public int JJTSENTENCIA_IF = 48;
  public int JJTSENTENCIA_WHILE = 49;
  public int JJTSENTENCIA_DO = 50;
  public int JJTSENTENCIA_FOR = 51;
  public int JJTSENTENCIA_BREAK = 52;
  public int JJTSENTENCIA_CONTINUE = 53;
  public int JJTSENTENCIA_RETURN = 54;
  public int JJTSENTENCIA_THROW = 55;
  public int JJTSENTENCIA_SYNCHRONIZED = 56;
  public int JJTSENTENCIA_TRY = 57;


  public String[] jjtNodeName = {
    "compilar",
    "identificador",
    "void",
    "LiteralInteger",
    "LiteralFloat",
    "LiteralCaracter",
    "LiteralString",
    "LiteralBoolean",
    "LiteralNull",
    "tipo",
    "tipo_primitivo",
    "campo_declaracion",
    "declarador_variable",
    "declarador_variable_id",
    "iniciar_variable",
    "asignacion",
    "op_mult_e",
    "op_add_e",
    "Or",
    "And",
    "BOr",
    "XOr",
    "BAnd",
    "IgualIgual",
    "NIgual",
    "Menor",
    "Mayor",
    "MenorEq",
    "MayorEq",
    "DespI",
    "DespD",
    "DespDNS",
    "Add",
    "Sub",
    "Mult",
    "Div",
    "Mod",
    "UnaryAdd",
    "UnarySub",
    "PlusPlus",
    "SubSub",
    "Comp",
    "Not",
    "expresion_asignacion",
    "sentencia_vacia",
    "expresion_sentencia",
    "sentencia_switch",
    "etiqueta_switch",
    "sentencia_if",
    "sentencia_while",
    "sentencia_do",
    "sentencia_for",
    "sentencia_break",
    "sentencia_continue",
    "sentencia_return",
    "sentencia_throw",
    "sentencia_synchronized",
    "sentencia_try",
  };
}
/* JavaCC - OriginalChecksum=f0710586be155b85fed77d41bf2e3261 (do not edit this line) */
