/* Generated By:JJTree: Do not edit this line. NodoLiteralCaracter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoLiteralCaracter extends SimpleNode {
  public NodoLiteralCaracter(int id) {
    super(id);
    value = ConstantesTipos.CHAR;
  }

  public NodoLiteralCaracter(Compilador p, int id) {
    super(p, id);
    value = ConstantesTipos.CHAR;
  }

  public void interpret()
  { 
	  
  }
}
/* JavaCC - OriginalChecksum=95d60962a16aeb761fa534ba5d097739 (do not edit this line) */
