/* Generated By:JJTree: Do not edit this line. NodoMayor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoMayor extends SimpleNode {
  public NodoMayor(int id) {
    super(id);
  }

  public NodoMayor(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=268e86c74e4317bf9cde49a91bbf3191 (do not edit this line) */
