/* Generated By:JJTree: Do not edit this line. Nodoexpresion_cond.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_cond extends SimpleNode {
  public Nodoexpresion_cond(int id) {
    super(id);
  }

  public Nodoexpresion_cond(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3ffc9adfcf00c7cb7979e9ed898519c8 (do not edit this line) */
