/* Generated By:JJTree: Do not edit this line. Nodoliteral_float.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoliteral_float extends SimpleNode {
  public Nodoliteral_float(int id) {
    super(id);
  }

  public Nodoliteral_float(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cbc78133f391ea59b911aa42d523cf5a (do not edit this line) */
