/* Generated By:JJTree: Do not edit this line. Nodosentencia_while.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodosentencia_while extends SimpleNode {
  public Nodosentencia_while(int id) {
    super(id);
  }

  public Nodosentencia_while(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2e145a89df09962f612e2ca794aafec1 (do not edit this line) */
