/* Generated By:JJTree: Do not edit this line. NodoMenor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoMenor extends SimpleNode {
  public NodoMenor(int id) {
    super(id);
  }

  public NodoMenor(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f32938bd3cc4462bd7951271a6a0bec4 (do not edit this line) */
