/* Generated By:JJTree: Do not edit this line. NodoMayorEq.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoMayorEq extends SimpleNode {
  public NodoMayorEq(int id) {
    super(id);
  }

  public NodoMayorEq(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9db8d91d90620158c9f0525c76cf5d88 (do not edit this line) */
