/* Generated By:JJTree: Do not edit this line. Nodoexpresion_cond_or.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_cond_or extends SimpleNode {
  public Nodoexpresion_cond_or(int id) {
    super(id);
  }

  public Nodoexpresion_cond_or(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7e715b6ca843ad8d7370f855a3b809d6 (do not edit this line) */
