/* Generated By:JJTree: Do not edit this line. Nodoexpresion_post.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_post extends SimpleNode {
  public Nodoexpresion_post(int id) {
    super(id);
  }

  public Nodoexpresion_post(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9a65ab8ffbd097104ac1ecec64e02e84 (do not edit this line) */
