/* Generated By:JJTree: Do not edit this line. Nodoexpresion_shift.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_shift extends SimpleNode {
  public Nodoexpresion_shift(int id) {
    super(id);
  }

  public Nodoexpresion_shift(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=44df6b7052c6d232b763a64d985c4954 (do not edit this line) */
