/* Generated By:JJTree: Do not edit this line. Nodosentencia_throw.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodosentencia_throw extends SimpleNode {
  public Nodosentencia_throw(int id) {
    super(id);
  }

  public Nodosentencia_throw(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eea1b63db9933634e5d42d2461e6b07e (do not edit this line) */
