/* Generated By:JJTree: Do not edit this line. NodoAdd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoAdd extends SimpleNode {
  public NodoAdd(int id) {
    super(id);
  }

  public NodoAdd(Compilador p, int id) {
    super(p, id);
  }
  
  public void interpret()
  { 
	 
	  
	  if( ! (	(jjtGetChild(0) instanceof NodoLiteralInteger || jjtGetChild(0) instanceof NodoLiteralFloat) && 
			  	(jjtGetChild(1) instanceof NodoLiteralInteger || jjtGetChild(1) instanceof NodoLiteralFloat))	){
		  
		  System.out.println("Error semántico: Los operadores no son de tipo numérico");
	  }
	  
		  
	  
//    stack[--top] = new Integer(((Integer)stack[top]).intValue() +
//    ((Integer)stack[top + 1]).intValue());
	  
  }
}
/* JavaCC - OriginalChecksum=d234078e2db31d4bbeb5371e3fc9611c (do not edit this line) */
