/* Generated By:JJTree: Do not edit this line. Nodooperador_asignacion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodooperador_asignacion extends SimpleNode {
  public Nodooperador_asignacion(int id) {
    super(id);
  }

  public Nodooperador_asignacion(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6dfd2c8efed29124dfde7ab161fcd30a (do not edit this line) */
