/* Generated By:JJTree: Do not edit this line. Nodoexpresion_mult.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_mult extends SimpleNode {
  public Nodoexpresion_mult(int id) {
    super(id);
  }

  public Nodoexpresion_mult(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cf85428bd2905846cd0a6bf80f53b095 (do not edit this line) */
