/* Generated By:JJTree: Do not edit this line. Nodoexpresion_pre_dec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_pre_dec extends SimpleNode {
  public Nodoexpresion_pre_dec(int id) {
    super(id);
  }

  public Nodoexpresion_pre_dec(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e6b1e3c24dcfdb8dce99958c47335a31 (do not edit this line) */
