/* Generated By:JJTree: Do not edit this line. Nodoexpresion_and_bin.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_and_bin extends SimpleNode {
  public Nodoexpresion_and_bin(int id) {
    super(id);
  }

  public Nodoexpresion_and_bin(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8992d93d4f261c9342ecb2b64bc9a5b4 (do not edit this line) */
