/* Generated By:JJTree: Do not edit this line. NodoDespDNS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoDespDNS extends SimpleNode {
  public NodoDespDNS(int id) {
    super(id);
  }

  public NodoDespDNS(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5cd2e679f3690e6de351e6f6556e6ab2 (do not edit this line) */
