/* Generated By:JJTree: Do not edit this line. Nodosentencia_switch.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodosentencia_switch extends SimpleNode {
  public Nodosentencia_switch(int id) {
    super(id);
  }

  public Nodosentencia_switch(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=50d718b7bcc97e2e6d9fccfbf7a9b49f (do not edit this line) */
