/* Generated By:JJTree: Do not edit this line. NodoSub.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoSub extends SimpleNode {
  public NodoSub(int id) {
    super(id);
    this.value = ConstantesTipos.INT;
  }

  public NodoSub(Compilador p, int id) {
    super(p, id);
    this.value = ConstantesTipos.INT;
  }
  
  public void interpret()
  { 
	 
	 super.comprobacionNumerica(); 
		  
	  
//    stack[--top] = new Integer(((Integer)stack[top]).intValue() +
//    ((Integer)stack[top + 1]).intValue());
	  
  }

}
/* JavaCC - OriginalChecksum=1e4879d1d2eccaec6e6dd4ac6a405f9d (do not edit this line) */
