/* Generated By:JJTree: Do not edit this line. NodoAdd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoAdd extends SimpleNode {
  public NodoAdd(int id) {
    super(id);
  }

  public NodoAdd(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=afbf188ebf46857c24821e5a7de526bf (do not edit this line) */
