/* Generated By:JJTree: Do not edit this line. Nodosentencia_break.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodosentencia_break extends SimpleNode {
  public Nodosentencia_break(int id) {
    super(id);
  }

  public Nodosentencia_break(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8df81387924171b6f9e867d9e3c9952e (do not edit this line) */
