/* Generated By:JJTree: Do not edit this line. Nodoexpresion_asignacion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_asignacion extends SimpleNode {
  public Nodoexpresion_asignacion(int id) {
    super(id);
  }

  public Nodoexpresion_asignacion(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=178d44f8291d173bbc2f84de4dba9585 (do not edit this line) */
