/* Generated By:JJTree: Do not edit this line. Nodoiniciar_variable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoiniciar_variable extends SimpleNode {
  public Nodoiniciar_variable(int id) {
    super(id);
  }

  public Nodoiniciar_variable(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b372fd2dc78ac2c28c277bad7ad411ee (do not edit this line) */
