/* Generated By:JJTree: Do not edit this line. NodoComp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoComp extends SimpleNode {
  public NodoComp(int id) {
    super(id);
  }

  public NodoComp(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=628bdc25fa012f7b240a9a315a764627 (do not edit this line) */
