/* Generated By:JJTree: Do not edit this line. NodoLiteralNull.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoLiteralNull extends SimpleNode {
  public NodoLiteralNull(int id) {
    super(id);
  }

  public NodoLiteralNull(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=958f0723ee0cc4d5ddb4c9dc8b39ff00 (do not edit this line) */
