/* Generated By:JJTree: Do not edit this line. Nodoexpresion_cond_and.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_cond_and extends SimpleNode {
  public Nodoexpresion_cond_and(int id) {
    super(id);
  }

  public Nodoexpresion_cond_and(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8293a0e21ae2b7e9e3bf7807648181c4 (do not edit this line) */
