/* Generated By:JJTree: Do not edit this line. NodoLiteralCaracter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoLiteralCaracter extends SimpleNode {
  public NodoLiteralCaracter(int id) {
    super(id);
  }

  public NodoLiteralCaracter(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b0218f2c3a3dd73eb3a84920b6a2fb6f (do not edit this line) */
