/* Generated By:JJTree: Do not edit this line. NodoAnd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoAnd extends SimpleNode {
  public NodoAnd(int id) {
    super(id);
    this.value = ConstantesTipos.BOOLEAN;
  }

  public NodoAnd(Compilador p, int id) {
    super(p, id);
    this.value = ConstantesTipos.BOOLEAN;
  }
  
  @Override
  public void interpret()
  { 
	  super.comprobacionBooleana();
  }

}
/* JavaCC - OriginalChecksum=d0b8a5c83c68b8997fc6132908c537ed (do not edit this line) */
