/* Generated By:JJTree: Do not edit this line. NodoMult.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoMult extends SimpleNode {
  public NodoMult(int id) {
    super(id);
    this.value = ConstantesTipos.INT;
  }

  public NodoMult(Compilador p, int id) {
    super(p, id);
    this.value = ConstantesTipos.INT;
  }
  
  public void interpret()
  { 
	 
	  
	  super.comprobacionNumerica(); 
	  
//    stack[--top] = new Integer(((Integer)stack[top]).intValue() +
//    ((Integer)stack[top + 1]).intValue());
	  
  }

}
/* JavaCC - OriginalChecksum=a7a29c340d63503b65aa35b004023e81 (do not edit this line) */
