/* Generated By:JJTree: Do not edit this line. Nodoasignacion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

import tabla.simbolos.Atributos;

public
class Nodoasignacion extends SimpleNode {
  public Nodoasignacion(int id) {
    super(id);
  }

  public Nodoasignacion(Compilador p, int id) {
    super(p, id);
  }
  
  public void interpret() {
	  SimpleNode n1 = null, n2 = null;
	  Atributos a1 = null, a2 = null;
	  
	  n1 = (SimpleNode) jjtGetChild(0);
	  n2 = (SimpleNode) jjtGetChild(1);
	  
	  // Interpretar sus 2 hijos, para comprobar sus tipos
	  n1.interpret();
	  n2.interpret();
	  
	  if (n1 instanceof Nodoidentificador){
		  System.out.println("Asignacion con identificador");
		  a1 = Compilador.gestorTS.getAtributos((String)n1.value);
		  if (a1 == null){
			  throw new RuntimeException("Error semántico: el identificador "+
					  (String)n1.value+" no existe en este ámbito o es un tipo.");
		  }
	  }
	  
	  if (n2 instanceof Nodoidentificador){
		  System.out.println("Asignacion con identificador");
		  a2 = Compilador.gestorTS.getAtributos((String)n2.value);
		  if (a2 == null){
			  throw new RuntimeException("Error semántico: el identificador "+
					  (String)n2.value+" no existe en este ámbito  o es un tipo.");
		  }
	  }
	  
	  if (a1 != null && a2 != null){
		  if (a1.getTipo() != a2.getTipo()){
			  throw new RuntimeException("Error semántico: no puede asignarse "+
					  (String)n2.value+" a "+(String)n1.value+" al tener distintos tipos.");
		  }
	  }
	  

  }

}
/* JavaCC - OriginalChecksum=90ac55abfb3ed5f52371f3ed38ec99c7 (do not edit this line) */
