/* Generated By:JJTree: Do not edit this line. Nodoexpresion_unaria.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_unaria extends SimpleNode {
  public Nodoexpresion_unaria(int id) {
    super(id);
  }

  public Nodoexpresion_unaria(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=646cbd7946c01fb4cbc46615100a1627 (do not edit this line) */
