/* Generated By:JJTree: Do not edit this line. Nodosentencia_synchronized.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodosentencia_synchronized extends SimpleNode {
  public Nodosentencia_synchronized(int id) {
    super(id);
  }

  public Nodosentencia_synchronized(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d464b7a7559222acb37b7086ac99ad61 (do not edit this line) */
