/* Generated By:JJTree: Do not edit this line. Nodosentencia_do.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodosentencia_do extends SimpleNode {
  public Nodosentencia_do(int id) {
    super(id);
  }

  public Nodosentencia_do(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c3ca77890796d9da7726d33b90a31350 (do not edit this line) */
