/* Generated By:JJTree: Do not edit this line. NodoLiteralBoolean.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoLiteralBoolean extends SimpleNode {
  public NodoLiteralBoolean(int id) {
    super(id);
  }

  public NodoLiteralBoolean(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6795aa693ffb3a98341eee9e6cc6f733 (do not edit this line) */
