/* Generated By:JJTree: Do not edit this line. Nodoexpresion_xor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_xor extends SimpleNode {
  public Nodoexpresion_xor(int id) {
    super(id);
  }

  public Nodoexpresion_xor(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8549c9986aad048331273be4da7bfb9e (do not edit this line) */
