/* Generated By:JJTree: Do not edit this line. Nodoexpresion_add.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_add extends SimpleNode {
  public Nodoexpresion_add(int id) {
    super(id);
  }

  public Nodoexpresion_add(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4778f8dffb583a0cbd8edd3e8871612c (do not edit this line) */
