/* Generated By:JJTree: Do not edit this line. NodoLiteralNull.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoLiteralNull extends SimpleNode {
  public NodoLiteralNull(int id) {
    super(id);
    this.value = ConstantesTipos.NULL;
  }

  public NodoLiteralNull(Compilador p, int id) {
    super(p, id);
    this.value = ConstantesTipos.NULL;
  }

}
/* JavaCC - OriginalChecksum=f1f2371aab48511ebfda92516f42e82d (do not edit this line) */
