/* Generated By:JJTree: Do not edit this line. Nododeclarador_variable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nododeclarador_variable extends SimpleNode {
  public Nododeclarador_variable(int id) {
    super(id);
  }

  public Nododeclarador_variable(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=88aee439cd0fe369b70775b59b399722 (do not edit this line) */
