/* Generated By:JJTree: Do not edit this line. Nodosentencia_try.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodosentencia_try extends SimpleNode {
  public Nodosentencia_try(int id) {
    super(id);
  }

  public Nodosentencia_try(Compilador p, int id) {
    super(p, id);
  }
  
  @Override
  public void interpret(){
	  
	  Compilador.gestorTS.nuevoAmbito("try");
	  System.out.println("Abriendo ambito: if");
	  int i, k = jjtGetNumChildren();

	     for (i = 0; i < k; i++)
	        jjtGetChild(i).interpret();
	     
     Compilador.gestorTS.cierraAmbito();
     System.out.println("Cerrando ambito: try");
  }

}
/* JavaCC - OriginalChecksum=4598def2cdc4a53cf4834a4e39766a03 (do not edit this line) */
