/* Generated By:JJTree: Do not edit this line. Nodoexpresion_post.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_post extends SimpleNode {
  public Nodoexpresion_post(int id) {
    super(id);
  }

  public Nodoexpresion_post(Compilador p, int id) {
    super(p, id);
  }
  
  public void interpret()
  {
     int i, k = jjtGetNumChildren();

     for (i = 0; i < k; i++)
        jjtGetChild(i).interpret();

  }

}
/* JavaCC - OriginalChecksum=94c9b1958b9e6793648568996a17ea9e (do not edit this line) */
