/* Generated By:JJTree: Do not edit this line. Nododeclaracion_variable_local.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nododeclaracion_variable_local extends SimpleNode {
  public Nododeclaracion_variable_local(int id) {
    super(id);
  }

  public Nododeclaracion_variable_local(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=85ee2688f0532f6e2746cebddf2022d5 (do not edit this line) */
