/* Generated By:JJTree: Do not edit this line. Nodosentencia_throw.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodosentencia_throw extends SimpleNode {
  public Nodosentencia_throw(int id) {
    super(id);
  }

  public Nodosentencia_throw(Compilador p, int id) {
    super(p, id);
  }
  
  public void interpret()
  {
     int i, k = jjtGetNumChildren();

     for (i = 0; i < k; i++)
        jjtGetChild(i).interpret();

  }

}
/* JavaCC - OriginalChecksum=dab70b62023fad2e12a62d20ff39f0b5 (do not edit this line) */
