/* Generated By:JJTree: Do not edit this line. NodoUnarySub.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoUnarySub extends SimpleNode {
  public NodoUnarySub(int id) {
    super(id);
  }

  public NodoUnarySub(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4f6b4c171c57f90ccb07a0ba33dfed86 (do not edit this line) */
