/* Generated By:JJTree: Do not edit this line. Nododeclarador_variable_id.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nododeclarador_variable_id extends SimpleNode {
  public Nododeclarador_variable_id(int id) {
    super(id);
  }

  public Nododeclarador_variable_id(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e96673192c7f01b1c12ff8df4b0b8f2b (do not edit this line) */
