/* Generated By:JJTree: Do not edit this line. NodoNot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoNot extends SimpleNode {
  public NodoNot(int id) {
    super(id);
  }

  public NodoNot(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d475bbd755ed88f48f10d2f16f90b8c6 (do not edit this line) */
