/* Generated By:JJTree: Do not edit this line. NodoDespI.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoDespI extends SimpleNode {
  public NodoDespI(int id) {
    super(id);
  }

  public NodoDespI(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c7fad2d31cb854604617cb8dec22401f (do not edit this line) */
