/* Generated By:JJTree: Do not edit this line. Nodoop_add_e.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoop_add_e extends SimpleNode {
  public Nodoop_add_e(int id) {
    super(id);
  }

  public Nodoop_add_e(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=238a982c683d01d63d003c8635eb2a88 (do not edit this line) */
