/* Generated By:JJTree: Do not edit this line. NodoMult.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoMult extends SimpleNode {
  public NodoMult(int id) {
    super(id);
  }

  public NodoMult(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4b44e4a190cf9ea0e74493ebc0fcdf49 (do not edit this line) */
