/* Generated By:JJTree: Do not edit this line. Nododeclarador_variable_id.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nododeclarador_variable_id extends SimpleNode {
	int type;
	String name;
	  
  public Nododeclarador_variable_id(int id) {
    super(id);
  }

  public Nododeclarador_variable_id(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=265a78532ed9fe4f80d1d6beac516403 (do not edit this line) */
