/* Generated By:JJTree: Do not edit this line. NodoMod.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoMod extends SimpleNode {
  public NodoMod(int id) {
    super(id);
  }

  public NodoMod(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bc8b5c1c1542ad4392c5c291841cf6ef (do not edit this line) */
