/* Generated By:JJTree: Do not edit this line. Nodobloque.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodobloque extends SimpleNode {
  public Nodobloque(int id) {
    super(id);
  }

  public Nodobloque(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=10763462d8fbfeb58f25cb29766fbce2 (do not edit this line) */
