/* Generated By:JJTree: Do not edit this line. NodoLiteralInteger.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoLiteralInteger extends SimpleNode {
  public NodoLiteralInteger(int id) {
    super(id);
    value = ConstantesTipos.INTEGER;
  }

  public NodoLiteralInteger(Compilador p, int id) {
    super(p, id);
    value = ConstantesTipos.INTEGER;
  }
  
  public void interpret()
  { 
	  
  }

}
/* JavaCC - OriginalChecksum=fe507747931805bdc01cac9eeec86b0c (do not edit this line) */
