/* Generated By:JJTree: Do not edit this line. Nodocompilar.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

import tabla.simbolos.v2.Atributos;

public
class Nodocompilar extends SimpleNode {
  public Nodocompilar(int id) {
    super(id);
  }

  public Nodocompilar(Compilador p, int id) {
    super(p, id);
  }
  
  public void interpret()
  {
	  Atributos.resetAliasCounter();
	  
	  int i, k = jjtGetNumChildren();

	  for (i = 0; i < k; i++)
	  {
		  System.out.print("Ejecutando:");
		  Token first  = ((SimpleNode)jjtGetChild(i)).jjtGetFirstToken();
		  Token last = ((SimpleNode)jjtGetChild(i)).jjtGetLastToken();
		  for (Token t = first; t != null; t = t.next)
		  {
			  System.out.print(" " + t);

			  if (t == last)
				  break;
		  }
		  System.out.println();

		  jjtGetChild(i).interpret();
	  }
	  
	  listErrSemantico();

  }

}
/* JavaCC - OriginalChecksum=297ca27b05a4a1e279d3a315d1fadbaa (do not edit this line) */
