/* Generated By:JJTree: Do not edit this line. Nodoexpresion_pre_inc.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_pre_inc extends SimpleNode {
  public Nodoexpresion_pre_inc(int id) {
    super(id);
  }

  public Nodoexpresion_pre_inc(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b1f35eb9a911ad76ada21a8117418425 (do not edit this line) */
