/* Generated By:JJTree: Do not edit this line. NodoBOr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoBOr extends SimpleNode {
  public NodoBOr(int id) {
    super(id);
  }

  public NodoBOr(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6583d36130c63038492cf5eb290e61e6 (do not edit this line) */
