/* Generated By:JJTree: Do not edit this line. NodoPlusPlus.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoPlusPlus extends SimpleNode {
  public NodoPlusPlus(int id) {
    super(id);
  }

  public NodoPlusPlus(Compilador p, int id) {
    super(p, id);
  }
  
  public void interpret()
  {
     int i, k = jjtGetNumChildren();

     for (i = 0; i < k; i++)
        jjtGetChild(i).interpret();

  }

}
/* JavaCC - OriginalChecksum=bdec5558bf7434dd4af32fc68eca7594 (do not edit this line) */
