/* Generated By:JJTree: Do not edit this line. Nodocompilar.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodocompilar extends SimpleNode {
  public Nodocompilar(int id) {
    super(id);
  }

  public Nodocompilar(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=150e734317f7d23789f8a2a3c9d6828f (do not edit this line) */
