/* Generated By:JJTree: Do not edit this line. Nodoasignacion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoasignacion extends SimpleNode {
  public Nodoasignacion(int id) {
    super(id);
  }

  public Nodoasignacion(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=faac876f2a58fbfe7cc54beb6de78081 (do not edit this line) */
