/* Generated By:JJTree: Do not edit this line. NodoLiteralString.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoLiteralString extends SimpleNode {
  public NodoLiteralString(int id) {
    super(id);
    this.value = ConstantesTipos.STRING;
  }

  public NodoLiteralString(Compilador p, int id) {
    super(p, id);
    
    this.value = ConstantesTipos.STRING;
  }
  
  public void interpret()
  { 
	  
  }

}
/* JavaCC - OriginalChecksum=c3d830b7485c07c3193ac76285ce7242 (do not edit this line) */
