/* Generated By:JJTree: Do not edit this line. Nododeclaracion_metodo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nododeclaracion_metodo extends SimpleNode {
  public Nododeclaracion_metodo(int id) {
    super(id);
  }

  public Nododeclaracion_metodo(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e7d93d282e1b0c942beb6dc404649ff7 (do not edit this line) */
