/* Generated By:JavaCC: Do not edit this line. CompiladorTreeConstants.java Version 5.0 */
package javacc;

public interface CompiladorTreeConstants
{
  public int JJTCOMPILAR = 0;
  public int JJTIDENTIFICADOR = 1;
  public int JJTVOID = 2;
  public int JJTLITERALINTEGER = 3;
  public int JJTLITERALFLOAT = 4;
  public int JJTLITERALCARACTER = 5;
  public int JJTLITERALSTRING = 6;
  public int JJTLITERALBOOLEAN = 7;
  public int JJTLITERALNULL = 8;
  public int JJTLITERAL_INTEGER = 9;
  public int JJTLITERAL_FLOAT = 10;
  public int JJTLITERAL_CARACTER = 11;
  public int JJTLITERAL_STRING = 12;
  public int JJTLITERAL_BOOLEAN = 13;
  public int JJTLITERAL_NULL = 14;
  public int JJTDECLARADOR_VARIABLE = 15;
  public int JJTDECLARADOR_VARIABLE_ID = 16;
  public int JJTINICIAR_VARIABLE = 17;
  public int JJTASIGNACION = 18;
  public int JJTOPERADOR_ASIGNACION = 19;
  public int JJTEXPRESION_COND = 20;
  public int JJTEXPRESION_COND_OR = 21;
  public int JJTOR = 22;
  public int JJTEXPRESION_COND_AND = 23;
  public int JJTAND = 24;
  public int JJTEXPRESION_OR_BIN = 25;
  public int JJTBOR = 26;
  public int JJTEXPRESION_XOR = 27;
  public int JJTXOR = 28;
  public int JJTEXPRESION_AND_BIN = 29;
  public int JJTBAND = 30;
  public int JJTEXPRESION_EQUAL = 31;
  public int JJTIGUAL = 32;
  public int JJTNIGUAL = 33;
  public int JJTEXPRESION_RELACIONAL = 34;
  public int JJTMENOR = 35;
  public int JJTMAYOR = 36;
  public int JJTMENOREQ = 37;
  public int JJTMAYOREQ = 38;
  public int JJTEXPRESION_SHIFT = 39;
  public int JJTDESPI = 40;
  public int JJTDESPD = 41;
  public int JJTDESPDNS = 42;
  public int JJTEXPRESION_ADD = 43;
  public int JJTADD = 44;
  public int JJTSUB = 45;
  public int JJTEXPRESION_MULT = 46;
  public int JJTMULT = 47;
  public int JJTDIV = 48;
  public int JJTMOD = 49;
  public int JJTEXPRESION_UNARIA = 50;
  public int JJTUNARYADD = 51;
  public int JJTUNARYSUB = 52;
  public int JJTEXPRESION_PRE_INC = 53;
  public int JJTPLUSPLUS = 54;
  public int JJTEXPRESION_PRE_DEC = 55;
  public int JJTSUBSUB = 56;
  public int JJTEXPRESION_UNARIA_DIF = 57;
  public int JJTCOMP = 58;
  public int JJTNOT = 59;
  public int JJTEXPRESION_POST = 60;
  public int JJTEXPRESION_ASIGNACION = 61;
  public int JJTBLOQUE = 62;
  public int JJTSENTENCIA_BLOQUE = 63;
  public int JJTDECLARACION_VARIABLE_LOCAL = 64;
  public int JJTSENTENCIA_VACIA = 65;
  public int JJTEXPRESION_SENTENCIA = 66;
  public int JJTSENTENCIA_SWITCH = 67;
  public int JJTETIQUETA_SWITCH = 68;
  public int JJTSENTENCIA_IF = 69;
  public int JJTSENTENCIA_WHILE = 70;
  public int JJTSENTENCIA_DO = 71;
  public int JJTSENTENCIA_FOR = 72;
  public int JJTSENTENCIA_BREAK = 73;
  public int JJTSENTENCIA_CONTINUE = 74;
  public int JJTSENTENCIA_RETURN = 75;
  public int JJTSENTENCIA_THROW = 76;
  public int JJTSENTENCIA_SYNCHRONIZED = 77;
  public int JJTSENTENCIA_TRY = 78;


  public String[] jjtNodeName = {
    "compilar",
    "identificador",
    "void",
    "LiteralInteger",
    "LiteralFloat",
    "LiteralCaracter",
    "LiteralString",
    "LiteralBoolean",
    "LiteralNull",
    "literal_integer",
    "literal_float",
    "literal_caracter",
    "literal_string",
    "literal_boolean",
    "literal_null",
    "declarador_variable",
    "declarador_variable_id",
    "iniciar_variable",
    "asignacion",
    "operador_asignacion",
    "expresion_cond",
    "expresion_cond_or",
    "Or",
    "expresion_cond_and",
    "And",
    "expresion_or_bin",
    "BOr",
    "expresion_xor",
    "XOr",
    "expresion_and_bin",
    "BAnd",
    "expresion_equal",
    "Igual",
    "NIgual",
    "expresion_relacional",
    "Menor",
    "Mayor",
    "MenorEq",
    "MayorEq",
    "expresion_shift",
    "DespI",
    "DespD",
    "DespDNS",
    "expresion_add",
    "Add",
    "Sub",
    "expresion_mult",
    "Mult",
    "Div",
    "Mod",
    "expresion_unaria",
    "UnaryAdd",
    "UnarySub",
    "expresion_pre_inc",
    "PlusPlus",
    "expresion_pre_dec",
    "SubSub",
    "expresion_unaria_dif",
    "Comp",
    "Not",
    "expresion_post",
    "expresion_asignacion",
    "bloque",
    "sentencia_bloque",
    "declaracion_variable_local",
    "sentencia_vacia",
    "expresion_sentencia",
    "sentencia_switch",
    "etiqueta_switch",
    "sentencia_if",
    "sentencia_while",
    "sentencia_do",
    "sentencia_for",
    "sentencia_break",
    "sentencia_continue",
    "sentencia_return",
    "sentencia_throw",
    "sentencia_synchronized",
    "sentencia_try",
  };
}
/* JavaCC - OriginalChecksum=e92613908c7589d8f134c9bec09755c8 (do not edit this line) */
