/* Generated By:JavaCC: Do not edit this line. CompiladorTreeConstants.java Version 5.0 */
package javacc;

public interface CompiladorTreeConstants
{
  public int JJTCOMPILAR = 0;
  public int JJTIDENTIFICADOR = 1;
  public int JJTVOID = 2;
  public int JJTLITERALINTEGER = 3;
  public int JJTLITERALFLOAT = 4;
  public int JJTLITERALCARACTER = 5;
  public int JJTLITERALSTRING = 6;
  public int JJTLITERALBOOLEAN = 7;
  public int JJTLITERALNULL = 8;
  public int JJTDECLARADOR_VARIABLE = 9;
  public int JJTDECLARADOR_VARIABLE_ID = 10;
  public int JJTINICIAR_VARIABLE = 11;
  public int JJTASIGNACION = 12;
  public int JJTOPERADOR_ASIGNACION = 13;
  public int JJTOR = 14;
  public int JJTAND = 15;
  public int JJTBOR = 16;
  public int JJTXOR = 17;
  public int JJTBAND = 18;
  public int JJTIGUAL = 19;
  public int JJTNIGUAL = 20;
  public int JJTMENOR = 21;
  public int JJTMAYOR = 22;
  public int JJTMENOREQ = 23;
  public int JJTMAYOREQ = 24;
  public int JJTDESPI = 25;
  public int JJTDESPD = 26;
  public int JJTDESPDNS = 27;
  public int JJTADD = 28;
  public int JJTSUB = 29;
  public int JJTMULT = 30;
  public int JJTDIV = 31;
  public int JJTMOD = 32;
  public int JJTUNARYADD = 33;
  public int JJTUNARYSUB = 34;
  public int JJTPLUSPLUS = 35;
  public int JJTSUBSUB = 36;
  public int JJTCOMP = 37;
  public int JJTNOT = 38;
  public int JJTEXPRESION_ASIGNACION = 39;
  public int JJTBLOQUE = 40;
  public int JJTSENTENCIA_BLOQUE = 41;
  public int JJTDECLARACION_VARIABLE_LOCAL = 42;
  public int JJTSENTENCIA_VACIA = 43;
  public int JJTEXPRESION_SENTENCIA = 44;
  public int JJTSENTENCIA_SWITCH = 45;
  public int JJTETIQUETA_SWITCH = 46;
  public int JJTSENTENCIA_IF = 47;
  public int JJTSENTENCIA_WHILE = 48;
  public int JJTSENTENCIA_DO = 49;
  public int JJTSENTENCIA_FOR = 50;
  public int JJTSENTENCIA_BREAK = 51;
  public int JJTSENTENCIA_CONTINUE = 52;
  public int JJTSENTENCIA_RETURN = 53;
  public int JJTSENTENCIA_THROW = 54;
  public int JJTSENTENCIA_SYNCHRONIZED = 55;
  public int JJTSENTENCIA_TRY = 56;


  public String[] jjtNodeName = {
    "compilar",
    "identificador",
    "void",
    "LiteralInteger",
    "LiteralFloat",
    "LiteralCaracter",
    "LiteralString",
    "LiteralBoolean",
    "LiteralNull",
    "declarador_variable",
    "declarador_variable_id",
    "iniciar_variable",
    "asignacion",
    "operador_asignacion",
    "Or",
    "And",
    "BOr",
    "XOr",
    "BAnd",
    "Igual",
    "NIgual",
    "Menor",
    "Mayor",
    "MenorEq",
    "MayorEq",
    "DespI",
    "DespD",
    "DespDNS",
    "Add",
    "Sub",
    "Mult",
    "Div",
    "Mod",
    "UnaryAdd",
    "UnarySub",
    "PlusPlus",
    "SubSub",
    "Comp",
    "Not",
    "expresion_asignacion",
    "bloque",
    "sentencia_bloque",
    "declaracion_variable_local",
    "sentencia_vacia",
    "expresion_sentencia",
    "sentencia_switch",
    "etiqueta_switch",
    "sentencia_if",
    "sentencia_while",
    "sentencia_do",
    "sentencia_for",
    "sentencia_break",
    "sentencia_continue",
    "sentencia_return",
    "sentencia_throw",
    "sentencia_synchronized",
    "sentencia_try",
  };
}
/* JavaCC - OriginalChecksum=9eb161935abf4f55f8d487279ee14c29 (do not edit this line) */
