/* Generated By:JavaCC: Do not edit this line. EG1TreeConstants.java Version 5.0 */
package javacc;

public interface EG1TreeConstants
{
  public int JJTROOT = 0;
  public int JJTIDENTIFICADOR = 1;
  public int JJTLITERAL = 2;
  public int JJTTIPO = 3;
  public int JJTTIPO_PRIMITIVO = 4;
  public int JJTDECLARACION_TIPO = 5;
  public int JJTTIPO_METODO = 6;
  public int JJTLISTA_DE_TIPOS = 7;
  public int JJTDECLARACION_CLASE = 8;
  public int JJTDECLARACION_CUERPO_CLASE = 9;
  public int JJTDECLARACIONR_METODO = 10;
  public int JJTDECLARACION_INTERFACE = 11;
  public int JJTDECLARACION_MIEMBRO_INTERFACE = 12;
  public int JJTCAMPO_DECLARACION = 13;
  public int JJTDECLARADOR_VARIABLE = 14;
  public int JJTDECLARADOR_VARIABLE_ID = 15;
  public int JJTINICIAR_VARIABLE = 16;
  public int JJTDECLARACION_METODO = 17;
  public int JJTDECLARADOR_METODO = 18;
  public int JJTPARAMETROS_FORMALES = 19;
  public int JJTPARAMETRO_FORMAL = 20;
  public int JJTDECLARACION_CONSTRUCTORA = 21;
  public int JJTCONST_EXPLIC = 22;
  public int JJTINICIALIZADOR_STATIC = 23;
  public int JJTEXPRESION = 24;
  public int JJTASIGNACION = 25;
  public int JJTOPERADOR_ASIGNACION = 26;
  public int JJTEXPRESION_COND = 27;
  public int JJTEXPRESION_COND_OR = 28;
  public int JJTOR = 29;
  public int JJTEXPRESION_COND_AND = 30;
  public int JJTAND = 31;
  public int JJTEXPRESION_OR_BIN = 32;
  public int JJTBOR = 33;
  public int JJTEXPRESION_XOR = 34;
  public int JJTXOR = 35;
  public int JJTEXPRESION_AND_BIN = 36;
  public int JJTBAND = 37;
  public int JJTEXPRESION_EQUAL = 38;
  public int JJTIGUAL = 39;
  public int JJTNIGUAL = 40;
  public int JJTEXPRESION_INSTANCEOF = 41;
  public int JJTEXPRESION_RELACIONAL = 42;
  public int JJTMENOR = 43;
  public int JJTMAYOR = 44;
  public int JJTMENOREQ = 45;
  public int JJTMAYOREQ = 46;
  public int JJTEXPRESION_SHIFT = 47;
  public int JJTDESPI = 48;
  public int JJTDESPD = 49;
  public int JJTDESPDNS = 50;
  public int JJTEXPRESION_ADD = 51;
  public int JJTADD = 52;
  public int JJTSUB = 53;
  public int JJTEXPRESION_MULT = 54;
  public int JJTMULT = 55;
  public int JJTDIV = 56;
  public int JJTMOD = 57;
  public int JJTEXPRESION_UNARIA = 58;
  public int JJTUNARYADD = 59;
  public int JJTUNARYSUB = 60;
  public int JJTEXPRESION_PRE_INC = 61;
  public int JJTPLUSPLUS = 62;
  public int JJTEXPRESION_PRE_DEC = 63;
  public int JJTSUBSUB = 64;
  public int JJTEXPRESION_UNARIA_DIF = 65;
  public int JJTCOMP = 66;
  public int JJTNOT = 67;
  public int JJTLOOK_CAST = 68;
  public int JJTEXPRESION_POST = 69;
  public int JJTEXPRESION_CAST = 70;
  public int JJTEXPRESION_PRIMARIA = 71;
  public int JJTPREFIJO_PRIMARIO = 72;
  public int JJTSUFIJO_PRIMARIO = 73;
  public int JJTARGUMENTOS = 74;
  public int JJTLISTA_ARGUMENTOS = 75;
  public int JJTEXPRESION_ASIGNACION = 76;
  public int JJTDIMENSIONES_ARRAY = 77;
  public int JJTSENTENCIA = 78;
  public int JJTSENTENCIA_ETIQUETA = 79;
  public int JJTBLOQUE = 80;
  public int JJTSENTENCIA_BLOQUE = 81;
  public int JJTDECLARACION_VARIABLE_LOCAL = 82;
  public int JJTSENTENCIA_VACIA = 83;
  public int JJTEXPRESION_SENTENCIA = 84;
  public int JJTSENTENCIA_SWITCH = 85;
  public int JJTETIQUETA_SWITCH = 86;
  public int JJTSENTENCIA_IF = 87;
  public int JJTSENTENCIA_WHILE = 88;
  public int JJTSENTENCIA_DO = 89;
  public int JJTSENTENCIA_FOR = 90;
  public int JJTLISTA_EXPRESION_SENTENCIA = 91;
  public int JJTINICIO_FOR = 92;
  public int JJTACTUALIZAR_FOR = 93;
  public int JJTSENTENCIA_BREAK = 94;
  public int JJTSENTENCIA_CONTINUE = 95;
  public int JJTSENTENCIA_RETURN = 96;
  public int JJTSENTENCIA_THROW = 97;
  public int JJTSENTENCIA_SYNCHRONIZED = 98;
  public int JJTSENTENCIA_TRY = 99;


  public String[] jjtNodeName = {
    "Root",
    "identificador",
    "literal",
    "tipo",
    "tipo_primitivo",
    "declaracion_tipo",
    "tipo_metodo",
    "lista_de_tipos",
    "declaracion_clase",
    "declaracion_cuerpo_clase",
    "declaracionR_metodo",
    "declaracion_interface",
    "declaracion_miembro_interface",
    "campo_declaracion",
    "declarador_variable",
    "declarador_variable_id",
    "iniciar_variable",
    "declaracion_metodo",
    "declarador_metodo",
    "parametros_formales",
    "parametro_formal",
    "declaracion_constructora",
    "const_explic",
    "inicializador_static",
    "expresion",
    "asignacion",
    "operador_asignacion",
    "expresion_cond",
    "expresion_cond_or",
    "Or",
    "expresion_cond_and",
    "And",
    "expresion_or_bin",
    "BOr",
    "expresion_xor",
    "XOr",
    "expresion_and_bin",
    "BAnd",
    "expresion_equal",
    "Igual",
    "NIgual",
    "expresion_instanceof",
    "expresion_relacional",
    "Menor",
    "Mayor",
    "MenorEq",
    "MayorEq",
    "expresion_shift",
    "DespI",
    "DespD",
    "DespDNS",
    "expresion_add",
    "Add",
    "Sub",
    "expresion_mult",
    "Mult",
    "Div",
    "Mod",
    "expresion_unaria",
    "UnaryAdd",
    "UnarySub",
    "expresion_pre_inc",
    "PlusPlus",
    "expresion_pre_dec",
    "SubSub",
    "expresion_unaria_dif",
    "Comp",
    "Not",
    "look_cast",
    "expresion_post",
    "expresion_cast",
    "expresion_primaria",
    "prefijo_primario",
    "sufijo_primario",
    "argumentos",
    "lista_argumentos",
    "expresion_asignacion",
    "dimensiones_array",
    "sentencia",
    "sentencia_etiqueta",
    "bloque",
    "sentencia_bloque",
    "declaracion_variable_local",
    "sentencia_vacia",
    "expresion_sentencia",
    "sentencia_switch",
    "etiqueta_switch",
    "sentencia_if",
    "sentencia_while",
    "sentencia_do",
    "sentencia_for",
    "lista_expresion_sentencia",
    "inicio_for",
    "actualizar_for",
    "sentencia_break",
    "sentencia_continue",
    "sentencia_return",
    "sentencia_throw",
    "sentencia_synchronized",
    "sentencia_try",
  };
}
/* JavaCC - OriginalChecksum=69f8b1df5cadf77a31fbf6f23ea43778 (do not edit this line) */
