/* Generated By:JJTree: Do not edit this line. NodoUnaryAdd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoUnaryAdd extends SimpleNode {
  public NodoUnaryAdd(int id) {
    super(id);
  }

  public NodoUnaryAdd(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=19f5204f580ba552c108c067157cd71b (do not edit this line) */
