/* Generated By:JJTree: Do not edit this line. Nodoexpresion_unaria_dif.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_unaria_dif extends SimpleNode {
  public Nodoexpresion_unaria_dif(int id) {
    super(id);
  }

  public Nodoexpresion_unaria_dif(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=942b1c079dd175c24154260f1ebb83bf (do not edit this line) */
