/* Generated By:JJTree: Do not edit this line. Nodosentencia_while.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodosentencia_while extends SimpleNode {
  public Nodosentencia_while(int id) {
    super(id);
  }

  public Nodosentencia_while(Compilador p, int id) {
    super(p, id);
  }
  
  @Override
  public void interpret(){
	  
	  int i, k = jjtGetNumChildren();

	     for (i = 0; i < k; i++)
	        jjtGetChild(i).interpret();
  }

}
/* JavaCC - OriginalChecksum=bd5d0dc119c8ec380549ff5ed572868f (do not edit this line) */
