/* Generated By:JJTree: Do not edit this line. Nodoetiqueta_switch.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoetiqueta_switch extends SimpleNode {
  public Nodoetiqueta_switch(int id) {
    super(id);
  }

  public Nodoetiqueta_switch(Compilador p, int id) {
    super(p, id);
  }

  public void interpret()
  {
     int i, k = jjtGetNumChildren();

     for (i = 0; i < k; i++)
        jjtGetChild(i).interpret();

  }
}
/* JavaCC - OriginalChecksum=514e3851c5745f04cac0bde488a47b49 (do not edit this line) */
