/* Generated By:JJTree: Do not edit this line. Nodoliteral_boolean.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoliteral_boolean extends SimpleNode {
  public Nodoliteral_boolean(int id) {
    super(id);
  }

  public Nodoliteral_boolean(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=00ff35741ee59295f3e342b5dcae2232 (do not edit this line) */
