/* Generated By:JJTree: Do not edit this line. Nodoexpresion_equal.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_equal extends SimpleNode {
  public Nodoexpresion_equal(int id) {
    super(id);
  }

  public Nodoexpresion_equal(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=55987bc8f1a7d3e02af1bfc1dc290a8e (do not edit this line) */
