/* Generated By:JJTree: Do not edit this line. Nodoexpresion_sentencia.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_sentencia extends SimpleNode {
  public Nodoexpresion_sentencia(int id) {
    super(id);
  }

  public Nodoexpresion_sentencia(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=839e9ec9c5780844c1e90e7f89525e70 (do not edit this line) */
