/* Generated By:JJTree: Do not edit this line. NodoComp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoComp extends SimpleNode {
  public NodoComp(int id) {
    super(id);
  }

  public NodoComp(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2465abf23b97c3ca48b0c6e1d12f2d6c (do not edit this line) */
