/* Generated By:JJTree: Do not edit this line. Nodoliteral_string.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoliteral_string extends SimpleNode {
  public Nodoliteral_string(int id) {
    super(id);
  }

  public Nodoliteral_string(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c5b612e07d39bc3cdbc0959db1758ebc (do not edit this line) */
