/* Generated By:JJTree: Do not edit this line. NodoDespD.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoDespD extends SimpleNode {
  public NodoDespD(int id) {
    super(id);
  }

  public NodoDespD(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2e5c51d2bdd07521a6873889c204470f (do not edit this line) */
