/* Generated By:JJTree: Do not edit this line. Nodoexpresion_instanceof.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_instanceof extends SimpleNode {
  public Nodoexpresion_instanceof(int id) {
    super(id);
  }

  public Nodoexpresion_instanceof(Compilador p, int id) {
    super(p, id);
  }
  
  public void interpret()
  {
	  SimpleNode n1, n2;
	  
	  n1 = (SimpleNode) children[0];
	  n2 = (SimpleNode) children[1];
	  
	  n1.interpret();
	  n2.interpret();
	 
	 if (n2 instanceof Nodoidentificador){
		 if (Compilador.gestorTS.estaLexema((String)n2.value)){
			 System.out.println("Error Semántico: instanceof debe referenciar un tipo no al identificador "+(String)n2.value);
		 }
	 }
	 
	 if (n1 instanceof Nodoidentificador){
		 if (!Compilador.gestorTS.estaLexema((String)n1.value)){
			 System.out.println("Error Semántico: instanceof, "+(String)n1.value+" no ha sido declarado");
		 }
	 }
	 else{
		 System.out.println("Error Semántico: el primer operando de instanceof debe ser un identificador, "+(String)n1.value+
				 " es incorrecto.");
	 }

  }

}
/* JavaCC - OriginalChecksum=267bebac47b6c9297aebe7f738e5a4ec (do not edit this line) */
