/* Generated By:JJTree: Do not edit this line. Nodoexpresion_sentencia.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_sentencia extends SimpleNode {
  public Nodoexpresion_sentencia(int id) {
    super(id);
  }

  public Nodoexpresion_sentencia(Compilador p, int id) {
    super(p, id);
  }

  public void interpret()
  {
	 
     int i, k = jjtGetNumChildren();

     for (i = 0; i < k; i++)
        jjtGetChild(i).interpret();

  }
}
/* JavaCC - OriginalChecksum=c15900e9d97f65c9cd21cc4e1de5d772 (do not edit this line) */
