/* Generated By:JJTree: Do not edit this line. NodoXOr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoXOr extends SimpleNode {
  public NodoXOr(int id) {
    super(id);
    this.value = ConstantesTipos.BOOLEAN;
  }

  public NodoXOr(Compilador p, int id) {
    super(p, id);
    this.value = ConstantesTipos.BOOLEAN;
  }

}
/* JavaCC - OriginalChecksum=46144f3b89fc659014d9096cb774d1f0 (do not edit this line) */
