/* Generated By:JJTree: Do not edit this line. NodoDespD.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoDespD extends SimpleNode {
  public NodoDespD(int id) {
    super(id);
  }

  public NodoDespD(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4ef32fe1236698fea8bc4fa3a1169b46 (do not edit this line) */
