/* Generated By:JJTree: Do not edit this line. Nodoop_mult_e.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoop_mult_e extends SimpleNode {
  public Nodoop_mult_e(int id) {
    super(id);
  }

  public Nodoop_mult_e(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e4e33b50f2023e069912d5987a0b8c3f (do not edit this line) */
