/* Generated By:JJTree: Do not edit this line. Nodoliteral_caracter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoliteral_caracter extends SimpleNode {
  public Nodoliteral_caracter(int id) {
    super(id);
  }

  public Nodoliteral_caracter(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=99f9d724ab15dc00e0a98effe432b54f (do not edit this line) */
