/* Generated By:JJTree: Do not edit this line. NodoMayorEq.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoMayorEq extends SimpleNode {
  public NodoMayorEq(int id) {
    super(id);
    this.value = ConstantesTipos.BOOLEAN;
  }

  public NodoMayorEq(Compilador p, int id) {
    super(p, id);
    this.value = ConstantesTipos.BOOLEAN;
  }

  public void interpret()
  {      
	 verificarComparacionValida();
  }
}
/* JavaCC - OriginalChecksum=d18f2ca56b63046bc30f14edf5905490 (do not edit this line) */
