/* Generated By:JJTree: Do not edit this line. Nodoop_equals.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoop_equals extends SimpleNode {
  public Nodoop_equals(int id) {
    super(id);
  }

  public Nodoop_equals(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c8feff7b4258397afecfea1942a92533 (do not edit this line) */
