/* Generated By:JJTree: Do not edit this line. NodoBOr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoBOr extends SimpleNode {
  public NodoBOr(int id) {
    super(id);
    this.value = ConstantesTipos.BOOLEAN;
  }

  public NodoBOr(Compilador p, int id) {
    super(p, id);
    this.value = ConstantesTipos.BOOLEAN;
  }

  @Override
  public void interpret()
  { 
	  super.comprobacionBooleana();
  }
}
/* JavaCC - OriginalChecksum=3ff9accd9b383844a5de933f8c867236 (do not edit this line) */
