/* Generated By:JJTree: Do not edit this line. Nodosentencia_return.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodosentencia_return extends SimpleNode {
  public Nodosentencia_return(int id) {
    super(id);
  }

  public Nodosentencia_return(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=087c3d6d1a00e59c282fe98aa00d1345 (do not edit this line) */
