/* Generated By:JJTree: Do not edit this line. Nodosentencia_bloque.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodosentencia_bloque extends SimpleNode {
  public Nodosentencia_bloque(int id) {
    super(id);
  }

  public Nodosentencia_bloque(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=329549a5b6856f0e24b3a313be194bd8 (do not edit this line) */
