/* Generated By:JJTree: Do not edit this line. Nodotipo_primitivo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodotipo_primitivo extends SimpleNode {
	
  public Nodotipo_primitivo(int id) {
    super(id);
  }

  public Nodotipo_primitivo(Compilador p, int id) {
    super(p, id);
  }
  
  public void interpret()
  {
	  //System.out.println("HOLA HOLA: "+nodeType);
	  
	  //pilaTipos.push(nodeType);
     
  }
}
/* JavaCC - OriginalChecksum=0074db8580e70e07ce4eed2293d9de72 (do not edit this line) */
