/* Generated By:JJTree: Do not edit this line. Nodoliteral_null.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoliteral_null extends SimpleNode {
  public Nodoliteral_null(int id) {
    super(id);
  }

  public Nodoliteral_null(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e21cc3b1adb51ce622b46c11fa197832 (do not edit this line) */
