/* Generated By:JJTree: Do not edit this line. NodoLiteralString.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoLiteralString extends SimpleNode {
  public NodoLiteralString(int id) {
    super(id);
  }

  public NodoLiteralString(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=22277ee1aadc195b3c54c273b30d5e84 (do not edit this line) */
