/* Generated By:JJTree: Do not edit this line. Nodosentencia_return.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodosentencia_return extends SimpleNode {
  public Nodosentencia_return(int id) {
    super(id);
  }

  public Nodosentencia_return(Compilador p, int id) {
    super(p, id);
  }
  
  @Override
  public void interpret(){
	  
	  int i, k = jjtGetNumChildren();

	     for (i = 0; i < k; i++)
	        jjtGetChild(i).interpret();
  }

}
/* JavaCC - OriginalChecksum=38cbab4f3b995f337c6ccbf7e6b06854 (do not edit this line) */
