/* Generated By:JJTree: Do not edit this line. NodoUnaryAdd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoUnaryAdd extends SimpleNode {
  public NodoUnaryAdd(int id) {
    super(id);
    this.value = ConstantesTipos.INT;
  }

  public NodoUnaryAdd(Compilador p, int id) {
    super(p, id);
    this.value = ConstantesTipos.INT;
  }

}
/* JavaCC - OriginalChecksum=38750567ee2a874ceb67ba6a8747499b (do not edit this line) */
