/* Generated By:JJTree: Do not edit this line. NodoMod.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoMod extends SimpleNode {
  public NodoMod(int id) {
    super(id);
    this.value = ConstantesTipos.INT;
  }

  public NodoMod(Compilador p, int id) {
    super(p, id);
    this.value = ConstantesTipos.INT;
  }
  
  public void interpret()
  {
     int i, k = jjtGetNumChildren();

     for (i = 0; i < k; i++)
        jjtGetChild(i).interpret();

  }

}
/* JavaCC - OriginalChecksum=b0b737f699b89cc98c51b5b471bc9273 (do not edit this line) */
