/* Generated By:JJTree: Do not edit this line. Nodoidentificador.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoidentificador extends SimpleNode {
	
  public Nodoidentificador(int id) {
    super(id);
  }

  public Nodoidentificador(Compilador p, int id) {
    super(p, id);
  }
  
  public void interpret()
  {  
	  if (parent instanceof Nodotipo){
		  ((Nodotipo) parent).value = value;
	  }
  }

}
/* JavaCC - OriginalChecksum=bfe882a411cf83819ce3dde45622a466 (do not edit this line) */
