/* Generated By:JJTree: Do not edit this line. Nodoliteral_integer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoliteral_integer extends SimpleNode {
  public Nodoliteral_integer(int id) {
    super(id);
  }

  public Nodoliteral_integer(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6ae4f7b24bf195a43c95be1286b1e4a0 (do not edit this line) */
