/* Generated By:JJTree: Do not edit this line. NodoNIgual.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoNIgual extends SimpleNode {
  public NodoNIgual(int id) {
    super(id);
  }

  public NodoNIgual(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=db53209a0891fd32368612e7d118adcb (do not edit this line) */
