/* Generated By:JJTree: Do not edit this line. Nododeclarador_metodo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

import java.util.ArrayList;

import tabla.simbolos.v2.Atributos;

public
class Nododeclarador_metodo extends SimpleNode {
	public ArrayList<Atributos> atribs = new ArrayList<Atributos>();
	
  public Nododeclarador_metodo(int id) {
    super(id);
  }

  public Nododeclarador_metodo(Compilador p, int id) {
    super(p, id);
  }
  
  public void interpret()
  {
	  if (Compilador.gestorTS.esLexemaValido((String)value)){
		  String tipoDevMetodo = (String)((Nodotipo_metodo)((Nododeclaracion_metodo)parent).children[0]).value;
		  
		  // Los nodos que estan entre el primero(nodo_tipo_metodo)y el último
		  // Los parametros se añadirán automaticamente a atribs
		  for (int i = 0; i < jjtGetNumChildren(); i++)
	          jjtGetChild(i).interpret();
		  
		  Atributos a = new Atributos((String)value, tipoDevMetodo, atribs);
		  Compilador.gestorTS.insertar((String)value, a);
	  }
	  else
		  addErrSemantico(lastToken.beginLine, "el método "+ value +" ya existe");
  }
}
/* JavaCC - OriginalChecksum=1c4a52c4f7f72a33c046bace0ef7c158 (do not edit this line) */
