/* Generated By:JJTree: Do not edit this line. NodoMenorEq.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoMenorEq extends SimpleNode {
  public NodoMenorEq(int id) {
    super(id);
    this.value = ConstantesTipos.BOOLEAN;
  }

  public NodoMenorEq(Compilador p, int id) {
    super(p, id);
    this.value = ConstantesTipos.BOOLEAN;
  }

  @Override
  public void interpret(){
	  verificarComparacionValida();
  }
}
/* JavaCC - OriginalChecksum=8c339f236bab847c993cf3ddfced5e8b (do not edit this line) */
