/* Generated By:JJTree: Do not edit this line. NodoSub.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoSub extends SimpleNode {
  public NodoSub(int id) {
    super(id);
  }

  public NodoSub(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9ecb707912e8c95e516b8dbdc4a5ad16 (do not edit this line) */
