/* Generated By:JJTree: Do not edit this line. NodoMenorEq.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoMenorEq extends SimpleNode {
  public NodoMenorEq(int id) {
    super(id);
  }

  public NodoMenorEq(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b4cd920f9bd6cde43ec6117189aa6035 (do not edit this line) */
