/* Generated By:JJTree: Do not edit this line. NodoBAnd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoBAnd extends SimpleNode {
  public NodoBAnd(int id) {
    super(id);
  }

  public NodoBAnd(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e34edc8bd2be344a874426fac545cd6a (do not edit this line) */
