/* Generated By:JJTree: Do not edit this line. Nodoidentificador.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoidentificador extends SimpleNode {
  public Nodoidentificador(int id) {
    super(id);
  }

  public Nodoidentificador(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e68f55b809ea076173100aba24d110c0 (do not edit this line) */
