/* Generated By:JJTree: Do not edit this line. Nodosentencia_for.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodosentencia_for extends SimpleNode {
  public Nodosentencia_for(int id) {
    super(id);
  }

  public Nodosentencia_for(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=52bc38f339f77ad064f7f6af7b1698a7 (do not edit this line) */
