/* Generated By:JJTree: Do not edit this line. NodoLiteralFloat.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoLiteralFloat extends SimpleNode {
  public NodoLiteralFloat(int id) {
    super(id);
  }

  public NodoLiteralFloat(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8b88e765ac4d96433d69b721d3c5bc7d (do not edit this line) */
