/* Generated By:JJTree: Do not edit this line. Nodoiniciar_variable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoiniciar_variable extends SimpleNode {
  public Nodoiniciar_variable(int id) {
    super(id);
  }

  public Nodoiniciar_variable(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b0c0f22543dbf4c7fc6fe8d1bb8cf79c (do not edit this line) */
