/* Generated By:JJTree: Do not edit this line. NodoSubSub.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoSubSub extends SimpleNode {
  public NodoSubSub(int id) {
    super(id);
  }

  public NodoSubSub(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=11767a3ad981778edcb40aed1a0f3daf (do not edit this line) */
