/* Generated By:JJTree: Do not edit this line. Nodoexpresion_or_bin.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodoexpresion_or_bin extends SimpleNode {
  public Nodoexpresion_or_bin(int id) {
    super(id);
  }

  public Nodoexpresion_or_bin(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cb00954eb5b956891550e23a2c890e1d (do not edit this line) */
