/* Generated By:JJTree: Do not edit this line. NodoDespDNS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoDespDNS extends SimpleNode {
  public NodoDespDNS(int id) {
    super(id);
  }

  public NodoDespDNS(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8b054c42adbb77b5df929d1bd4eadfdc (do not edit this line) */
