/* Generated By:JJTree: Do not edit this line. NodoLiteralBoolean.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoLiteralBoolean extends SimpleNode {
  public NodoLiteralBoolean(int id) {
    super(id);
    value = ConstantesTipos.BOOLEAN;
  }

  public NodoLiteralBoolean(Compilador p, int id) {
    super(p, id);
    value = ConstantesTipos.BOOLEAN;
  }

  public void interpret()
  { 
	  
  }
}
/* JavaCC - OriginalChecksum=dc5d0333e87510e46d963e86b3bb2f9f (do not edit this line) */
