/* Generated By:JJTree: Do not edit this line. Nodosentencia_vacia.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodosentencia_vacia extends SimpleNode {
  public Nodosentencia_vacia(int id) {
    super(id);
  }

  public Nodosentencia_vacia(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=95afd67c5f50dae1b609961b9be558f2 (do not edit this line) */
