/* Generated By:JJTree: Do not edit this line. Nodobloque.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodobloque extends SimpleNode {
  public Nodobloque(int id) {
    super(id);
  }

  public Nodobloque(Compilador p, int id) {
    super(p, id);
  }
  
  public void interpret()
  {
     int i, k = jjtGetNumChildren();

     for (i = 0; i < k; i++)
        jjtGetChild(i).interpret();

  }

}
/* JavaCC - OriginalChecksum=dd293d1c2cc8f0084b62366ec997cb31 (do not edit this line) */
