/* Generated By:JJTree: Do not edit this line. Nodosentencia_do.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodosentencia_do extends SimpleNode {
  public Nodosentencia_do(int id) {
    super(id);
  }

  public Nodosentencia_do(Compilador p, int id) {
    super(p, id);
  }
  
  
  @Override
  public void interpret(){
	  
	  int i, k = jjtGetNumChildren();

	     for (i = 0; i < k; i++)
	        jjtGetChild(i).interpret();
  }

}
/* JavaCC - OriginalChecksum=507b7c41c9f20034d008a7010924b022 (do not edit this line) */
