/* Generated By:JJTree: Do not edit this line. NodoBAnd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoBAnd extends SimpleNode {
  public NodoBAnd(int id) {
    super(id);
  }

  public NodoBAnd(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d7b5e43ec777f2fdf34e999a1ea53d78 (do not edit this line) */
