/* Generated By:JJTree&JavaCC: Do not edit this line. CompiladorConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGITO = 9;
  /** RegularExpression Id. */
  int LETRA = 10;
  /** RegularExpression Id. */
  int ABSTRACT = 11;
  /** RegularExpression Id. */
  int BOOLEAN = 12;
  /** RegularExpression Id. */
  int BREAK = 13;
  /** RegularExpression Id. */
  int CASE = 14;
  /** RegularExpression Id. */
  int CATCH = 15;
  /** RegularExpression Id. */
  int CHAR = 16;
  /** RegularExpression Id. */
  int CLASS = 17;
  /** RegularExpression Id. */
  int CONST = 18;
  /** RegularExpression Id. */
  int CONTINUE = 19;
  /** RegularExpression Id. */
  int DEFAULT_PLG = 20;
  /** RegularExpression Id. */
  int DO = 21;
  /** RegularExpression Id. */
  int DOUBLE = 22;
  /** RegularExpression Id. */
  int ELSE = 23;
  /** RegularExpression Id. */
  int ENUM = 24;
  /** RegularExpression Id. */
  int EXTENDS = 25;
  /** RegularExpression Id. */
  int FINAL = 26;
  /** RegularExpression Id. */
  int FINALLY = 27;
  /** RegularExpression Id. */
  int FLOAT = 28;
  /** RegularExpression Id. */
  int FOR = 29;
  /** RegularExpression Id. */
  int GOTO = 30;
  /** RegularExpression Id. */
  int IF = 31;
  /** RegularExpression Id. */
  int IMPLEMENTS = 32;
  /** RegularExpression Id. */
  int IMPORT = 33;
  /** RegularExpression Id. */
  int INSTANCEOF = 34;
  /** RegularExpression Id. */
  int INT = 35;
  /** RegularExpression Id. */
  int INTERFACE = 36;
  /** RegularExpression Id. */
  int LONG = 37;
  /** RegularExpression Id. */
  int NEW = 38;
  /** RegularExpression Id. */
  int PACKAGE = 39;
  /** RegularExpression Id. */
  int PRIVATE = 40;
  /** RegularExpression Id. */
  int PROTECTED = 41;
  /** RegularExpression Id. */
  int PUBLIC = 42;
  /** RegularExpression Id. */
  int RETURN = 43;
  /** RegularExpression Id. */
  int SHORT = 44;
  /** RegularExpression Id. */
  int STATIC = 45;
  /** RegularExpression Id. */
  int SUPER = 46;
  /** RegularExpression Id. */
  int SWITCH = 47;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 48;
  /** RegularExpression Id. */
  int THIS = 49;
  /** RegularExpression Id. */
  int THROW = 50;
  /** RegularExpression Id. */
  int THROWS = 51;
  /** RegularExpression Id. */
  int TRY = 52;
  /** RegularExpression Id. */
  int VOID = 53;
  /** RegularExpression Id. */
  int VOLATILE = 54;
  /** RegularExpression Id. */
  int WHILE = 55;
  /** RegularExpression Id. */
  int TRUE = 56;
  /** RegularExpression Id. */
  int FALSE = 57;
  /** RegularExpression Id. */
  int LITERAL_INTEGER = 58;
  /** RegularExpression Id. */
  int LITERAL_INTEGER_ERROR = 59;
  /** RegularExpression Id. */
  int LITERAL_FLOAT = 60;
  /** RegularExpression Id. */
  int LITERAL_CARACTER = 61;
  /** RegularExpression Id. */
  int LITERAL_STRING = 62;
  /** RegularExpression Id. */
  int LITERAL_BOOLEAN = 63;
  /** RegularExpression Id. */
  int LITERAL_NULL = 64;
  /** RegularExpression Id. */
  int PAR_A = 65;
  /** RegularExpression Id. */
  int PAR_C = 66;
  /** RegularExpression Id. */
  int LLAVE_A = 67;
  /** RegularExpression Id. */
  int LLAVE_C = 68;
  /** RegularExpression Id. */
  int COR_A = 69;
  /** RegularExpression Id. */
  int COR_C = 70;
  /** RegularExpression Id. */
  int PYC = 71;
  /** RegularExpression Id. */
  int COMA = 72;
  /** RegularExpression Id. */
  int PUNTO = 73;
  /** RegularExpression Id. */
  int PYP = 74;
  /** RegularExpression Id. */
  int PREG = 75;
  /** RegularExpression Id. */
  int OR = 76;
  /** RegularExpression Id. */
  int AND = 77;
  /** RegularExpression Id. */
  int OR_B = 78;
  /** RegularExpression Id. */
  int AND_B = 79;
  /** RegularExpression Id. */
  int IGUAL = 80;
  /** RegularExpression Id. */
  int N_IGUAL = 81;
  /** RegularExpression Id. */
  int MENOR = 82;
  /** RegularExpression Id. */
  int MAYOR = 83;
  /** RegularExpression Id. */
  int MENOR_EQ = 84;
  /** RegularExpression Id. */
  int MAYOR_EQ = 85;
  /** RegularExpression Id. */
  int ADD = 86;
  /** RegularExpression Id. */
  int SUB = 87;
  /** RegularExpression Id. */
  int MULT = 88;
  /** RegularExpression Id. */
  int DIV = 89;
  /** RegularExpression Id. */
  int MOD = 90;
  /** RegularExpression Id. */
  int PLUS_PLUS = 91;
  /** RegularExpression Id. */
  int SUB_SUB = 92;
  /** RegularExpression Id. */
  int NOT = 93;
  /** RegularExpression Id. */
  int ADD_E = 94;
  /** RegularExpression Id. */
  int SUB_E = 95;
  /** RegularExpression Id. */
  int MULT_E = 96;
  /** RegularExpression Id. */
  int DIV_E = 97;
  /** RegularExpression Id. */
  int MOD_E = 98;
  /** RegularExpression Id. */
  int AND_E = 99;
  /** RegularExpression Id. */
  int OR_E = 100;
  /** RegularExpression Id. */
  int EQUALS = 101;
  /** RegularExpression Id. */
  int DESP_D = 102;
  /** RegularExpression Id. */
  int DESP_I = 103;
  /** RegularExpression Id. */
  int DESP_DNS = 104;
  /** RegularExpression Id. */
  int XOR = 105;
  /** RegularExpression Id. */
  int COMP = 106;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 107;
  /** RegularExpression Id. */
  int IDENTIFICADOR_ERROR_1 = 108;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int EntreComentarios = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "<DIGITO>",
    "<LETRA>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"new\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"true\"",
    "\"false\"",
    "<LITERAL_INTEGER>",
    "<LITERAL_INTEGER_ERROR>",
    "<LITERAL_FLOAT>",
    "<LITERAL_CARACTER>",
    "<LITERAL_STRING>",
    "<LITERAL_BOOLEAN>",
    "\"null\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "\"?\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"!\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"&=\"",
    "\"|=\"",
    "\"=\"",
    "\">>\"",
    "\"<<\"",
    "\">>>\"",
    "\"^\"",
    "\"~\"",
    "<IDENTIFICADOR>",
    "<IDENTIFICADOR_ERROR_1>",
  };

}
