/* Generated By:JJTree: Do not edit this line. Nodocampo_declaracion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodocampo_declaracion extends SimpleNode {
  public Nodocampo_declaracion(int id) {
    super(id);
  }

  public Nodocampo_declaracion(Compilador p, int id) {
    super(p, id);
  }

  public void interpret()
  {
     int i, k = jjtGetNumChildren();

     for (i = 0; i < k; i++)
        jjtGetChild(i).interpret();

  }
}
/* JavaCC - OriginalChecksum=06b730100180e13dddded3193a092a66 (do not edit this line) */
