/* Generated By:JJTree: Do not edit this line. NodoOr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoOr extends SimpleNode {
  public NodoOr(int id) {
    super(id);
  }

  public NodoOr(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=59110293b7ef56c56cef18777a63637e (do not edit this line) */
