/* Generated By:JJTree: Do not edit this line. NodoLiteralFloat.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoLiteralFloat extends SimpleNode {
  public NodoLiteralFloat(int id) {
    super(id);
  }

  public NodoLiteralFloat(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c0254fc4044fc9ad20ed1efcc72fcaab (do not edit this line) */
