/* Generated By:JJTree: Do not edit this line. NodoIgual.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class NodoIgual extends SimpleNode {
  public NodoIgual(int id) {
    super(id);
  }

  public NodoIgual(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=34b1d8ac2b966d68084f4ddaa23444bb (do not edit this line) */
