/* Generated By:JJTree: Do not edit this line. Nodosentencia_bloque.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Nodo,NODE_EXTENDS=XNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class Nodosentencia_bloque extends SimpleNode {
  public Nodosentencia_bloque(int id) {
    super(id);
  }

  public Nodosentencia_bloque(Compilador p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5e78f78c417d50413f88b12d6cf822c1 (do not edit this line) */
